# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab1d509059869e9ea28dde250c2b864d45202af06eb9087b7f6ccfc1263402eeb44789d8aa561b4598e074203b623966376dd47a3d58296a546b40a3d73ad28

test:
  secret_key_base: 64105604d605a7ba734137a71a69ca36e5c18699dca7c48e5b683e077773ac475ab983301b50da765d2e12ff9ce6a6f60af17bcc0531286c281e92654e679165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
